openapi: 3.0.0
info:
  title: Zaakregistratiecomponent (ZRC) API
  description: Een API om een zaakregistratiecomponent te benaderen
  contact:
    url: 'https://github.com/VNG-Realisatie/gemma-zaken'
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:
  - basic: []
paths:
  '/betrokkenen/{id}':
    get:
      operationId: organisatorischeeenheid_read
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisatorischeEenheid'
      tags:
        - betrokkenen
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this Organisatorische eenheid.
        required: true
        schema:
          type: integer
  /klantcontacten:
    post:
      operationId: klantcontact_create
      description: >-
        Registreer een klantcontact bij een ZAAK.


        Indien geen identificatie gegeven is, dan wordt deze automatisch
        gegenereerd.
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KlantContact'
      tags:
        - klantcontacten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KlantContact'
        required: true
    parameters: []
  '/klantcontacten/{id}':
    get:
      operationId: klantcontact_read
      description: Geef de details van een klantcontact voor een ZAAK.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KlantContact'
      tags:
        - klantcontacten
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this klantcontact.
        required: true
        schema:
          type: integer
  /rollen:
    post:
      operationId: rol_create
      description: Koppel een BETROKKENE aan een ZAAK.
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rol'
      tags:
        - rollen
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rol'
        required: true
    parameters: []
  '/rollen/{id}':
    get:
      operationId: rol_read
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rol'
      tags:
        - rollen
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this Rol.
        required: true
        schema:
          type: integer
  /statussen:
    post:
      operationId: status_create
      description: ''
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - statussen
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
        required: true
    parameters: []
  '/statussen/{id}':
    get:
      operationId: status_read
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - statussen
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this status.
        required: true
        schema:
          type: integer
  /zaakobjecten:
    post:
      operationId: zaakobject_create
      description: Registreer een ZAAKOBJECT relatie.
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZaakObject'
      tags:
        - zaakobjecten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZaakObject'
        required: true
    parameters: []
  '/zaakobjecten/{id}':
    get:
      operationId: zaakobject_read
      description: Geef de details van een ZAAKOBJECT relatie.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZaakObject'
      tags:
        - zaakobjecten
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this zaakobject.
        required: true
        schema:
          type: integer
  /zaken:
    post:
      operationId: zaak_create
      description: >-
        Maak een ZAAK aan.


        Indien geen zaakidentificatie gegeven is, dan wordt deze automatisch
        gegenereerd.
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - zaken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zaak'
        required: true
    parameters: []
  '/zaken/{id}':
    get:
      operationId: zaak_read
      description: Opvragen en bewerken van ZAAKen.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - zaken
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this zaak.
        required: true
        schema:
          type: integer
  '/zaken/{zaak_pk}/zaakeigenschappen':
    get:
      operationId: zaakeigenschap_list
      description: Geef een collectie van eigenschappen behorend bij een ZAAK.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ZaakEigenschap'
      tags:
        - zaken
    post:
      operationId: zaakeigenschap_create
      description: Registreer een eigenschap van een ZAAK.
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZaakEigenschap'
      tags:
        - zaken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZaakEigenschap'
        required: true
    parameters:
      - name: zaak_pk
        in: path
        required: true
        schema:
          type: string
  '/zaken/{zaak_pk}/zaakeigenschappen/{id}':
    get:
      operationId: zaakeigenschap_read
      description: Geef de details van ZaakEigenschap voor een ZAAK.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZaakEigenschap'
      tags:
        - zaken
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this zaakeigenschap.
        required: true
        schema:
          type: integer
      - name: zaak_pk
        in: path
        required: true
        schema:
          type: string
servers:
  - url: /api/v1
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
  schemas:
    OrganisatorischeEenheid:
      required:
        - organisatieEenheidIdentificatie
        - organisatieIdentificatie
        - datumOntstaan
        - naam
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        organisatieEenheidIdentificatie:
          title: Organisatie eenheid identificatie
          description: Een korte identificatie van de organisatorische eenheid.
          type: string
          maxLength: 24
          minLength: 1
        organisatieIdentificatie:
          title: Organisatie identificatie
          description: >-
            Het RSIN van de organisatie zijnde een Niet-natuurlijk persoon
            waarvan de ORGANISATORISCHE EENHEID deel uit maakt.
          type: integer
          maximum: 2147483647
          minimum: 0
        datumOntstaan:
          title: Datum ontstaan
          description: De datum wrop de organisatorische eenheid is ontstaan.
          type: string
          format: date
        naam:
          title: Naam
          description: De feitelijke naam van de organisatorische eenheid.
          type: string
          maxLength: 50
          minLength: 1
    KlantContact:
      required:
        - zaak
        - datumtijd
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        identificatie:
          title: Identificatie
          description: De unieke aanduiding van een KLANTCONTACT
          type: string
          maxLength: 14
          minLength: 1
        datumtijd:
          title: Datumtijd
          description: De datum en het tijdstip waarop het KLANTCONTACT begint
          type: string
          format: date-time
        kanaal:
          title: Kanaal
          description: Het communicatiekanaal waarlangs het KLANTCONTACT gevoerd wordt
          type: string
          maxLength: 20
    Rol:
      required:
        - zaak
        - betrokkene
        - rolomschrijving
        - rolomschrijvingGeneriek
        - roltoelichting
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        betrokkene:
          title: Betrokkene
          type: string
          format: uri
        rolomschrijving:
          title: Rolomschrijving
          description: Algemeen gehanteerde benaming van de aard van de ROL
          type: string
          enum:
            - Adviseur
            - Behandelaar
            - Belanghebbende
            - Beslisser
            - Initiator
            - Klantcontacter
            - Zaakcoördinator
        rolomschrijvingGeneriek:
          title: Rolomschrijving generiek
          description: Algemeen gehanteerde benaming van de aard van de ROL
          type: string
          enum:
            - Adviseur
            - Behandelaar
            - Belanghebbende
            - Beslisser
            - Initiator
            - Klantcontacter
            - Zaakcoördinator
            - Mede-initiator
        roltoelichting:
          title: Roltoelichting
          type: string
          maxLength: 1000
          minLength: 1
    Status:
      required:
        - zaak
        - statusType
        - datumStatusGezet
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        statusType:
          title: Status type
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        datumStatusGezet:
          title: Datum status gezet
          description: De datum waarop de ZAAK de status heeft verkregen.
          type: string
          format: date-time
        statustoelichting:
          title: Statustoelichting
          description: >-
            Een, voor de initiator van de zaak relevante, toelichting op de
            status van een zaak.
          type: string
          maxLength: 1000
    ZaakObject:
      required:
        - zaak
        - object
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        object:
          title: Object
          description: URL naar de resource die het OBJECT beschrijft.
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        relatieomschrijving:
          title: Relatieomschrijving
          description: Omschrijving van de betrekking tussen de ZAAK en het OBJECT.
          type: string
          maxLength: 80
    Zaak:
      required:
        - zaaktype
        - registratiedatum
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaakidentificatie:
          title: Zaakidentificatie
          description: >-
            De unieke identificatie van de ZAAK binnen de organisatie die
            verantwoordelijk is voor de behandeling van de ZAAK.
          type: string
          maxLength: 40
        zaaktype:
          title: Zaaktype
          description: URL naar het zaaktype in de CATALOGUS waar deze voorkomt
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        registratiedatum:
          title: Registratiedatum
          description: >-
            De datum waarop de zaakbehandelende organisatie de ZAAK heeft
            geregistreerd
          type: string
          format: date
        toelichting:
          title: Toelichting
          description: Een toelichting op de zaak.
          type: string
          maxLength: 1000
        zaakgeometrie:
          title: Zaakgeometrie
          description: 'Punt, lijn of (multi-)vlak geometrie-informatie, in GeoJSON.'
          type: object
        status:
          title: Status
          description: 'Indien geen status bekend is, dan is de waarde ''null'''
          type: string
          format: uri
          readOnly: true
    ZaakEigenschap:
      required:
        - zaak
        - eigenschap
        - waarde
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        eigenschap:
          title: Eigenschap
          description: URL naar de eigenschap in het ZTC
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        waarde:
          title: Waarde
          type: string
          minLength: 1
