openapi: "3.0.0"
info:
  title: Zaak registratie API
  description: Een API om een zaakregistratiecomponent te kunnen benaderen
  version: 1.0.0
  contact:
    url:  https://github.com/VNG-Realisatie/gemma-zaken
paths:
  '/api/v{version}/zaken':
    post:
      summary: Aanmaken nieuwe zaak
      operationId: aanmakenZaak
      description: Maakt een nieuwe zaak aan en retourneert de toegekende zaak identificatie wanneer de zaak succesvol is aangemaakt.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zaak'
      responses:
        201:
          description: "Zaakidentificatie"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZaakId'
        422:
          description: Opgegeven zaak informatie kan niet verwerkt worden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
        default:
          description: Onverwachte fout tijdens opvoeren zaak
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
  '/api/v{version}/zaakinformatieobjecten':
    post:
      summary: Voeg een informatieobject toe aan de zaak
      operationId: zaakinformatieobject_create
      description: Voeg een informatieobject toe aan een zaak
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZaakInformatieObject'
      responses:
        201:
          description: ZaakInformatieObject is succesvol aangemaakt.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/ZaakInformatieObject'
        422:
          description: Opgegeven zaakinformatieobject kan niet verwerkt worden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
        default:
          description: Onverwachte fout tijdens opvoeren informatieobject
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
servers:
  - url: /
components:
  schemas:
    Zaak:
      description: Een zaak
      properties:
        type:
          description: URL naar het zaaktype van de zaak
          type: string
        omschrijving:
          description: Omschrijving of toelichting op de zaak
          type: string
        initiator:
          $ref: '#/components/schemas/Subject'
        status:
          description: URL naar de status van de zaak
          type: string
        registratiedatum:
          description: Tijdstip waarop de zaak is geregistreerd
          type: string
          format: 'date-time'
        kanaal:
          description: Kanaal via welke de zaak is gemeld
          type: string
        locatie:
          description: Coordinate van de locatie waarop de zaak betrekking heeft in Well Known Text (WKT) formaat
          type: string
        objecten:
          description: Lijst met URL's naar aan de zaak gerelateerde objecten
          type: array
          items:
            type: string
        zaakgegevens:
          description: Domein specifieke gegevens beheorende bij de zaak
          type: array
          items:
            $ref: '#/components/schemas/Zaakgegeven'
      required:
      - type
      - omschrijving
    ZaakId:
      description: zaakidentificatie
      properties:
        zaakidentificatie:
          type: string
          description: zaakidentificatie
    Subject:
      description: Een persoon of bedrijf
      properties:
        email:
          description: e-mail adres
          type: string
          format: email
        telefoonnummer:
          description: telefoonnummer
          type: string
    Zaakgegeven:
      description: Domein specifiek gegeven behorende bij een zaak
      properties:
        naam:
          description: Naam van het gegeven
          type: string
        waarde:
          description: Waarde van het gegeven
          type: string
        type:
          description: Type van de waarde van het gegeven
          type: string
          enum:
          - tekst
          - nummer
          - datum
          - datumtijd
          - ja_nee
      required:
      - naam
      - waarde
      - type
    ZaakInformatieObject:
      required:
        - zaak
        - informatieobject
      description: Een aan een zaak gerelateerd informatieobject (document, foto end.)
      properties:
        zaak:
          title: Zaak
          description: URL naar de zaak horend bij dit ZAAKINFORMATIEOBJECT
          type: string
          format: uri
        informatieobject:
          title: informatieobject
          description: URL naar het informatieobject horend bij dit ZAAKINFORMATIEOBJECT
          type: string
          format: uri
    Fout:
      description: Een opgetreden fout
      properties:
        title:
          description: Wat er is misgegaan
          type: string
        status:
          description: HTTP Response code
          type: integer
        detail:
          description: Meer details over de fout
          type: string
        invalid-params:
          description: Lijst met fouten in invoer parameters
          type: object
          properties:
            name:
              description: Naam van de parameter met invalide inhoud
              type: string
            reason:
              description: Wat er mis is met de inhoud van de parameter
              type: string
