openapi: "3.0.0"
info:
  title: Zaak registratie API
  description: Een API om een zaakregistratiecomponent te kunnen benaderen
  version: 1.0.0
  contact:
    url:  https://github.com/VNG-Realisatie/gemma-zaken
paths:
  '/api/v{version}/zaken':
    post:
      summary: Aanmaken nieuwe zaak
      operationId: zaak_create
      description: >-
        Maak een ZAAK aan.

        Indien geen zaakidentificatie gegeven is, dan wordt deze automatisch
        gegenereerd.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zaak'
      responses:
        201:
          description: "Representatie van aangemaakte ZAAK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
        422:
          description: Opgegeven zaak informatie kan niet verwerkt worden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
        default:
          description: Onverwachte fout tijdens opvoeren zaak
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
  '/api/v{version}/zaakinformatieobjecten':
    post:
      summary: Voeg een informatieobject toe aan de zaak
      operationId: zaakinformatieobject_create
      description: Voeg een informatieobject toe aan een zaak
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZaakInformatieObject'
      responses:
        201:
          description: ZaakInformatieObject is succesvol aangemaakt.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/ZaakInformatieObject'
        422:
          description: Opgegeven zaakinformatieobject kan niet verwerkt worden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
        default:
          description: Onverwachte fout tijdens opvoeren informatieobject
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fout'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
servers:
  - url: /
components:
  schemas:
    Zaak:
      description: Een ZAAK
      required:
        - zaaktype
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaakidentificatie:
          title: Zaakidentificatie
          description: >-
            De unieke identificatie van de ZAAK binnen de organisatie die
            verantwoordelijk is voor de behandeling van de ZAAK.
          type: string
          maxLength: 40
        zaaktype:
          title: Zaaktype
          description: URL naar het zaaktype in de CATALOGUS waar deze voorkomt
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        status:
          title: Status
          description: 'Indien geen status bekend is, dan is de waarde ''null'''
          type: string
          format: uri
          readOnly: true
        omschrijving:
          title: Omschrijving
          description: Een korte omschrijving van de zaak.
          type: string
          maxLength: 80
        # TODO: in het RGBZ 2.0 model loopt dit via de rollen/betrokkenen
        # initiator:
        #   title: Initiator
        #   description: URL naar de initiator van de ZAAK.
        #   type: string
        #   format: url
        registratiedatum:
          title: Registratiedatum
          description: De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd
          type: string
          format: 'date'
        # TODO: volgens RGBZ 2.0 komt kanaal uit KLANTCONTACT
        # kanaal:
        #   description: Kanaal via welke de zaak is gemeld
        #   type: string
        zaakgeometrie:  # NOTE: komt ook voor bij OBJECT
          title: Zaakgeometrie
          description: Punt, lijn of multi-vlak geometrie-informatie, in WKT formaat.
          type: string
        objecten:
          title: OBJECTen
          description: Lijst met URL's naar aan de zaak gerelateerde objecten
          type: array
          items:
            type: string
    ZaakInformatieObject:
      required:
        - zaak
        - informatieobject
      description: Een aan een zaak gerelateerd informatieobject (document, foto end.)
      properties:
        zaak:
          title: Zaak
          description: URL naar de zaak horend bij dit ZAAKINFORMATIEOBJECT
          type: string
          format: uri
        informatieobject:
          title: informatieobject
          description: URL naar het informatieobject horend bij dit ZAAKINFORMATIEOBJECT
          type: string
          format: uri
    # BETROKKENE?
    # Subject:
    #   description: Een persoon of bedrijf
    #   properties:
    #     email:
    #       description: e-mail adres
    #       type: string
    #       format: email
    #     telefoonnummer:
    #       description: telefoonnummer
    #       type: string
    Fout:
      description: Een opgetreden fout
      properties:
        title:
          description: Wat er is misgegaan
          type: string
        status:
          description: HTTP Response code
          type: integer
        detail:
          description: Meer details over de fout
          type: string
        invalid-params:
          description: Lijst met fouten in invoer parameters
          type: object
          properties:
            name:
              description: Naam van de parameter met invalide inhoud
              type: string
            reason:
              description: Wat er mis is met de inhoud van de parameter
              type: string
