# Inspired by https://docs.docker.com/compose/django/

# This is for development purposes ONLY. Do NOT run this in production with
# the same SECRET_KEYs.

version: '3.4'

services:
  # databases
  zrc_db:
    image: mdillon/postgis
    volumes:
      - zrc_postgres_data:/var/lib/postgresql/data

  drc_db:
    image: postgres
    volumes:
      - drc_postgres_data:/var/lib/postgresql/data

  ztc_db:
    image: postgres
    volumes:
      - ztc_postgres_data:/var/lib/postgresql/data

  # web
  zrc_web:
    image: nlxio/gemma-zrc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=zrc.conf.docker
      - SECRET_KEY=c1zqz%y-s-$$63ca_abc8dmfjno#&pk!wy8k9f8c*4w@(whxy1n'
      - DATABASE_HOST=zrc_db
    ports:
      - 8000:8000
    depends_on:
      - zrc_db

  drc_web:
    image: nlxio/gemma-drc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.docker
      - SECRET_KEY=h1kluf9r2yhcfr_i!fqb!srx=!u@!^b_gdl54=h0n15j34*+#=
      - DATABASE_HOST=drc_db
    ports:
      - 8001:8000
    depends_on:
      - drc_db

  ztc_web:
    image: nlxio/gemma-ztc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.docker
      - SECRET_KEY=)lwxn07vp1+ru=yf^n+v4l&ij24l3vhhitw9vk4=0ix14ibmfj
      - DATABASE_HOST=ztc_db
    ports:
      - 8002:8000
    depends_on:
      - ztc_db

volumes:
  zrc_postgres_data:
  drc_postgres_data:
  ztc_postgres_data:
