---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zrc
  namespace: gemma
  labels:
    k8s-app: zrc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: zrc
  template:
    metadata:
      name: zrc
      labels:
        k8s-app: zrc
    spec:
      containers:
      - name: zrc
        image: vngr/gemma-zrc:0.2.1
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: zrc.conf.docker
          - name: SUBPATH
            value: /zrc
          - name: DATABASE_HOST
            value: postgres-zrc
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DATABASE_PASSWORD
            value: <REDACTED>
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: zrc
  namespace: gemma
  labels:
    k8s-app: zrc
spec:
  selector:
    k8s-app: zrc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
