---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres-nc
  namespace: gemma
  labels:
    k8s-app: postgres-nc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: postgres-nc
  template:
    metadata:
      name: postgres-nc
      labels:
        k8s-app: postgres-nc
    spec:
      volumes:
      - name: data
        hostPath:
          path: "/storage/gemma-postgres-nc"
          type: ''
      containers:
      - name: postgres
        image: postgres:11
        env:
          - name: POSTGRES_PASSWORD
            value: <REDACTED>
        volumeMounts:
          - name: data
            mountPath: "/var/lib/postgresql/data"

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: postgres-nc
  namespace: gemma
  labels:
    k8s-app: postgres-nc
spec:
  selector:
    k8s-app: postgres-nc
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
