---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zaken-docs
  namespace: gemma
  labels:
    k8s-app: zaken-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: zaken-docs
  template:
    metadata:
      name: zaken-docs
      labels:
        k8s-app: zaken-docs
    spec:
      containers:
      - name: zaken-docs
        image: vngr/gemma-zaken-docs:latest

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: zaken-docs
  namespace: gemma
  labels:
    k8s-app: zaken-docs
spec:
  selector:
    k8s-app: zaken-docs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
